version: "3.2"
services:
  api:
    build: .
    command: uvicorn api.main:app --reload --host 0.0.0.0 --port 8000
    env_file: dev.env
    expose:
      - 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/code
  bot:
    build: .
    command: python bot.py
    env_file: dev.env
    restart: always
    volumes:
      - .:/code
